[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Workspace,
    [string]$TargetRoot = (Get-Location).Path,
    [switch]$CloneMissing,
    [switch]$FetchExisting,
    [switch]$IncludeClaudeSettings,
    [switch]$SkipClaudeSettings,
    [switch]$SkipGraphBuild
)

Import-Module (Join-Path $PSScriptRoot 'Helix.Tools.psm1') -Force

function Test-HelixPlaceholderValue {
    param([string]$Value)

    if ([string]::IsNullOrWhiteSpace($Value)) {
        return $true
    }

    return $Value -match 'your-org' -or $Value -in @(
        'example-feature',
        'service-a',
        'web-app',
        'Example Feature',
        'Short description of the feature-space',
        'One-sentence desired outcome'
    )
}

function Assert-RegistryAndWorkspaceReady {
    param(
        [Parameter(Mandatory = $true)]$Registry,
        [Parameter(Mandatory = $true)][string]$RegistryManifestName,
        [Parameter(Mandatory = $true)]$WorkspaceManifest,
        [Parameter(Mandatory = $true)][string]$WorkspaceName
    )

    if (-not $Registry.repos -or @($Registry.repos).Count -eq 0) {
        throw "$RegistryManifestName does not define any repos. Update the registry before running setup-workspace.ps1."
    }

    $seenIds = @{}
    $seenPaths = @{}

    foreach ($repo in $Registry.repos) {
        $repoId = [string]$repo.id
        $remote = [string]$repo.remote
        $localPath = [string]$repo.local_path

        if ([string]::IsNullOrWhiteSpace($repoId)) {
            throw "$RegistryManifestName contains a repo entry without an id."
        }

        if ([string]::IsNullOrWhiteSpace($remote)) {
            throw "Repo '$repoId' is missing a remote in $RegistryManifestName."
        }

        if ([string]::IsNullOrWhiteSpace($localPath)) {
            throw "Repo '$repoId' is missing a local_path in $RegistryManifestName."
        }

        if ($seenIds.ContainsKey($repoId)) {
            throw "Duplicate repo id '$repoId' in $RegistryManifestName."
        }
        $seenIds[$repoId] = $true

        if ($seenPaths.ContainsKey($localPath)) {
            throw "Duplicate repo local_path '$localPath' in $RegistryManifestName."
        }
        $seenPaths[$localPath] = $true

        if (Test-HelixPlaceholderValue -Value $remote) {
            throw "Repo '$repoId' in $RegistryManifestName still uses a template placeholder remote ('$remote'). Update helix-repos.yml before running setup-workspace.ps1."
        }
    }

    if (-not $WorkspaceManifest.repos -or @($WorkspaceManifest.repos).Count -eq 0) {
        throw "Workspace '$WorkspaceName' does not define any repos. Update the workspace manifest before running setup-workspace.ps1."
    }

    foreach ($workspaceRepo in $WorkspaceManifest.repos) {
        $repoId = [string]$workspaceRepo.repo_id
        if ([string]::IsNullOrWhiteSpace($repoId)) {
            throw "Workspace '$WorkspaceName' contains a repo entry without repo_id."
        }
    }
}

function Get-WorkspaceRepoRelativePath {
    param(
        [Parameter(Mandatory = $true)][string]$WorkspaceName,
        [Parameter(Mandatory = $true)][string]$RepoId
    )

    return "workspaces/$WorkspaceName/repos/$RepoId"
}

function Resolve-HelixTemplatePath {
    param(
        [Parameter(Mandatory = $true)][string]$HelixRoot,
        [Parameter(Mandatory = $true)][string]$TemplateFileName
    )

    $candidates = @(
        (Join-Path $HelixRoot "helix/templates/$TemplateFileName"),
        (Join-Path $HelixRoot "templates/$TemplateFileName")
    )

    foreach ($candidate in $candidates) {
        if (Test-Path $candidate) {
            return $candidate
        }
    }

    throw "Could not resolve template '$TemplateFileName'. Checked: $($candidates -join ', ')"
}

function New-GeneratedInstructionSummaryFile {
    param(
        [Parameter(Mandatory = $true)][string]$OutputPath,
        [Parameter(Mandatory = $true)][string]$ApplyTo,
        [Parameter(Mandatory = $true)][string]$Title,
        [AllowEmptyCollection()][object[]]$Sections = @()
    )

    $lines = @(
        '---',
        "applyTo: `"$ApplyTo`"",
        '---',
        '',
        '<!-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. -->',
        '<!-- Generated by helix/scripts/setup-workspace.ps1 -->',
        '',
        "# $Title",
        ''
    )

    if (@($Sections).Count -eq 0) {
        $lines += '_No instruction sources found._'
        $lines += ''
    } else {
        foreach ($section in $Sections) {
            $lines += "## $($section.name)"
            $lines += ''
            if (-not [string]::IsNullOrWhiteSpace([string]$section.content)) {
                $lines += @([string]$section.content -split "`r?`n")
            }
            $lines += ''
        }
    }

    $parent = Split-Path -Parent $OutputPath
    if ($parent) {
        [System.IO.Directory]::CreateDirectory($parent) | Out-Null
    }

    [System.IO.File]::WriteAllText($OutputPath, ($lines -join [Environment]::NewLine) + [Environment]::NewLine)
}

function Test-HelixCrgImport {
    param(
        [Parameter(Mandatory = $true)][string]$Command,
        [string[]]$Arguments = @()
    )

    try {
        $allArgs = @($Arguments) + @('-c', 'import code_review_graph')
        & $Command @allArgs *> $null
        return $LASTEXITCODE -eq 0
    } catch {
        return $false
    }
}

function Get-HelixCrgRunner {
    if ((Get-Command python -ErrorAction SilentlyContinue) -and (Test-HelixCrgImport -Command 'python')) {
        return [ordered]@{ command = 'python'; args = @() }
    }

    if ((Get-Command py -ErrorAction SilentlyContinue) -and (Test-HelixCrgImport -Command 'py' -Arguments @('-3'))) {
        return [ordered]@{ command = 'py'; args = @('-3') }
    }

    if ((Get-Command python3 -ErrorAction SilentlyContinue) -and (Test-HelixCrgImport -Command 'python3')) {
        return [ordered]@{ command = 'python3'; args = @() }
    }

    return $null
}

function Invoke-HelixCrgBuild {
    param(
        [Parameter(Mandatory = $true)][string]$RepoPath,
        [Parameter(Mandatory = $true)][System.Collections.IDictionary]$Runner
    )

    $cmd = [string]$Runner['command']
    $prefix = @($Runner['args']) + @('-m', 'code_review_graph')

    Write-Host "  CRG: build --repo $RepoPath (--skip-flows for speed; run /build-graph later for flows)"
    & $cmd @prefix 'build' '--repo' $RepoPath '--skip-flows' 2>&1 | Write-Host
    $buildExit = $LASTEXITCODE

    if ($buildExit -ne 0) {
        return [ordered]@{ status = 'failed'; stage = 'build'; exit_code = $buildExit }
    }

    & $cmd @prefix 'register' $RepoPath 2>&1 | Write-Host
    $registerExit = $LASTEXITCODE

    & $cmd @prefix 'wiki' '--repo' $RepoPath 2>&1 | Write-Host
    $wikiExit = $LASTEXITCODE

    return [ordered]@{
        status = 'built'
        stage = 'wiki'
        register_exit = $registerExit
        wiki_exit = $wikiExit
    }
}

$TargetRoot = Get-HelixRoot -StartPath $TargetRoot
$registryResolution = Resolve-HelixRegistryPath -HelixRoot $TargetRoot
$registryPath = [string]$registryResolution.path
$registryManifestName = [string]$registryResolution.display_name
if ($registryResolution.source -eq 'legacy') {
    Write-Warning "Using legacy registry manifest 'repos.yml'. Rename it to 'helix-repos.yml' when practical."
}

$workspacePath = Get-HelixWorkspaceManifestPath -HelixRoot $TargetRoot -Workspace $Workspace
$workspaceDir = Split-Path -Parent $workspacePath
$workspaceName = Split-Path $workspaceDir -Leaf

$registry = Import-HelixYamlFile -Path $registryPath
$workspaceManifest = Import-HelixYamlFile -Path $workspacePath

Assert-RegistryAndWorkspaceReady -Registry $registry -RegistryManifestName $registryManifestName -WorkspaceManifest $workspaceManifest -WorkspaceName $workspaceName

$repoIndex = @{}
foreach ($repo in $registry.repos) {
    $repoIndex[[string]$repo.id] = $repo
}

$workspaceFileBaseDir = $TargetRoot
$folders = @(
    [ordered]@{
        name = Split-Path $TargetRoot -Leaf
        path = Get-HelixRelativePath -BasePath $workspaceFileBaseDir -TargetPath $TargetRoot
    }
)

$repoStates = @()
$workspaceRepos = @()
$crgResults = @()

$crgModePath = Join-Path $TargetRoot '.helix/context-providers.yml'
$crgMode = 'off'
if (Test-Path $crgModePath) {
    try {
        $crgConfig = Import-HelixYamlFile -Path $crgModePath
        if ($crgConfig.providers -and $crgConfig.providers.code_review_graph -and $crgConfig.providers.code_review_graph.mode) {
            $crgMode = [string]$crgConfig.providers.code_review_graph.mode
        }
    } catch {
        Write-Warning "Could not parse '$crgModePath': $($_.Exception.Message). CRG build will be skipped."
    }
}

$crgRunner = $null
if (-not $SkipGraphBuild -and $crgMode -eq 'mcp') {
    $crgRunner = Get-HelixCrgRunner
    if ($null -eq $crgRunner) {
        Write-Warning "CRG mode is 'mcp' but no python runner with code_review_graph was found. Skipping graph build. Install via './helix/scripts/set-context-provider.ps1 -Mode mcp -Bootstrap' or pass -SkipGraphBuild to silence."
    }
}

foreach ($workspaceRepo in $workspaceManifest.repos) {
    $repoId = [string]$workspaceRepo.repo_id
    if (-not $repoIndex.ContainsKey($repoId)) {
        throw "Workspace '$workspaceName' references repo_id '$repoId' that is not present in $registryManifestName."
    }

    $repoDef = $repoIndex[$repoId]
    $repoRelativePath = Get-WorkspaceRepoRelativePath -WorkspaceName $workspaceName -RepoId $repoId
    $repoPath = Join-Path $TargetRoot $repoRelativePath
    $repoDir = Split-Path -Parent $repoPath

    if (-not (Test-Path $repoPath) -and $CloneMissing) {
        New-HelixDirectory -Path $repoDir
        Write-Host "Cloning $repoId into $repoPath"
        & git clone ([string]$repoDef.remote) $repoPath
        if ($LASTEXITCODE -ne 0) {
            throw "git clone failed for '$repoId'."
        }

        $branch = if ($workspaceRepo.Contains('branch') -and $workspaceRepo.branch) { [string]$workspaceRepo.branch } elseif ($repoDef.Contains('default_branch') -and $repoDef.default_branch) { [string]$repoDef.default_branch } elseif ($registry.defaults.default_branch) { [string]$registry.defaults.default_branch } else { 'main' }
        if ($branch -and $branch -ne 'main') {
            & git -C $repoPath checkout $branch
        }
    } elseif ((Test-Path $repoPath) -and $FetchExisting) {
        Write-Host "Fetching $repoId"
        & git -C $repoPath fetch
    }

    $folders += [ordered]@{
        name = $repoId
        path = Get-HelixRelativePath -BasePath $workspaceFileBaseDir -TargetPath $repoPath
    }

    $repoState = Get-HelixRepoReadiness -RepoId $repoId -RepoPath $repoPath
    $repoState.local_path = $repoRelativePath
    if ($repoDef.Contains('remote')) {
        $repoState.git.remote = [string]$repoDef.remote
    }
    $repoStates += $repoState

    $capabilityState = Get-HelixRepoCapabilities -RepoId $repoId -RepoPath $repoPath
    $capabilityState.local_path = $repoRelativePath

    $workspaceRepos += [ordered]@{
        repo_id = $repoId
        repo_path = $repoPath
        repo_relative_path = $repoRelativePath
    }

    $repoStatePath = Join-Path $TargetRoot ".helix/repo-state/$repoId.yml"
    Write-HelixYamlFile -Path $repoStatePath -Value $repoState

    $repoCapabilityPath = Join-Path $TargetRoot ".helix/repo-capabilities/$repoId.yml"
    Write-HelixYamlFile -Path $repoCapabilityPath -Value $capabilityState

    if ($repoState.present -and -not $SkipGraphBuild -and $crgMode -eq 'mcp' -and $null -ne $crgRunner) {
        try {
            $buildResult = Invoke-HelixCrgBuild -RepoPath $repoPath -Runner $crgRunner
        } catch {
            $buildResult = [ordered]@{ status = 'failed'; stage = 'build'; exit_code = -1; reason = $_.Exception.Message }
        }
        $crgResults += [pscustomobject]@{
            Repo = $repoId
            Status = $buildResult.status
            Stage = $buildResult.stage
            Detail = if ($buildResult.Contains('reason')) { $buildResult.reason } elseif ($buildResult.Contains('exit_code')) { "exit:$($buildResult.exit_code)" } else { '' }
        }
    }
}

$verificationPolicyDeclared = $false
$verificationPolicyPath = $null
if ($null -ne $workspaceManifest.artifacts -and $workspaceManifest.artifacts.Contains('verification_policy')) {
    $verificationPolicyArtifact = [string]$workspaceManifest.artifacts['verification_policy']
    if (-not [string]::IsNullOrWhiteSpace($verificationPolicyArtifact)) {
        $verificationPolicyDeclared = $true
        $verificationPolicyPath = if ([System.IO.Path]::IsPathRooted($verificationPolicyArtifact)) {
            [System.IO.Path]::GetFullPath($verificationPolicyArtifact)
        } else {
            [System.IO.Path]::GetFullPath((Join-Path $workspaceDir $verificationPolicyArtifact))
        }
    }
}

if ($verificationPolicyDeclared -and -not (Test-Path $verificationPolicyPath)) {
    $verificationPolicyTemplatePath = Resolve-HelixTemplatePath -HelixRoot $TargetRoot -TemplateFileName 'verification-policy.yml.template'
    $verificationPolicyDir = Split-Path -Parent $verificationPolicyPath
    if ($verificationPolicyDir) {
        New-HelixDirectory -Path $verificationPolicyDir
    }

    Copy-Item -LiteralPath $verificationPolicyTemplatePath -Destination $verificationPolicyPath -Force
    try {
        $verificationPolicy = Import-HelixYamlFile -Path $verificationPolicyPath
        $verificationPolicy.workspace_id = $workspaceName
        $verificationPolicy.last_seeded_at = (Get-Date).ToUniversalTime().ToString('o')
        Write-HelixYamlFile -Path $verificationPolicyPath -Value $verificationPolicy
    } catch {
        Write-Warning "Seeded verification policy at '$verificationPolicyPath' from template, but could not apply workspace metadata."
    }
}

$mentalModelPath = Join-Path $workspaceDir 'mental-model.md'
if (-not (Test-Path $mentalModelPath)) {
    $mentalModelTemplatePath = Resolve-HelixTemplatePath -HelixRoot $TargetRoot -TemplateFileName 'mental-model.md.template'
    Copy-Item -LiteralPath $mentalModelTemplatePath -Destination $mentalModelPath -Force
}

$workspaceConfig = [ordered]@{
    folders = $folders
    settings = [ordered]@{
        'chat.agentFilesLocations' = @(
            [ordered]@{ source = '.github/agents' }
        )
        'chat.skillsLocations' = @(
            [ordered]@{ source = '.github/skills' }
        )
        'chat.hookFilesLocations' = @(
            [ordered]@{ source = '.github/hooks' }
        )
    }
}

$workspaceFile = Join-Path $TargetRoot "$workspaceName.code-workspace"
$workspaceConfig | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $workspaceFile

$activeWorkspace = [ordered]@{
    schema_version = 1
    active = $workspaceName
    updated_at = (Get-Date).ToUniversalTime().ToString('o')
}
Write-HelixYamlFile -Path (Join-Path $TargetRoot '.helix/active-workspace.yml') -Value $activeWorkspace

if ($SkipClaudeSettings) {
    Write-Warning "SkipClaudeSettings is deprecated because Claude settings are no longer written by default. Use -IncludeClaudeSettings when you explicitly want Claude Desktop configuration."
}

if ($IncludeClaudeSettings) {
    $claudeDir = Join-Path $TargetRoot '.claude'
    New-HelixDirectory -Path $claudeDir
    $settingsPath = Join-Path $claudeDir 'settings.local.json'
    $additionalDirs = @()
    foreach ($workspaceRepoEntry in $workspaceRepos) {
        $additionalDirs += [string]$workspaceRepoEntry.repo_relative_path
    }

    $settings = [ordered]@{
        permissions = [ordered]@{
            additionalDirectories = $additionalDirs
        }
    }
    $settings | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $settingsPath
}

$instructionsRoot = Join-Path $TargetRoot '.github/instructions'
New-HelixDirectory -Path $instructionsRoot

$workspaceInstructionSections = @()
$workspaceAgentsPath = Join-Path $workspaceDir 'AGENTS.md'
if (Test-Path $workspaceAgentsPath) {
    $workspaceInstructionSections += [ordered]@{
        name = "Workspace AGENTS.md ($workspaceAgentsPath)"
        content = [System.IO.File]::ReadAllText($workspaceAgentsPath)
    }
}

$workspaceInstructionPath = Join-Path $instructionsRoot "$workspaceName.workspace.instructions.md"
New-GeneratedInstructionSummaryFile `
    -OutputPath $workspaceInstructionPath `
    -ApplyTo "workspaces/$workspaceName/repos/**" `
    -Title "Workspace instructions for $workspaceName" `
    -Sections $workspaceInstructionSections

foreach ($workspaceRepoEntry in $workspaceRepos) {
    $repoId = [string]$workspaceRepoEntry.repo_id
    $repoPath = [string]$workspaceRepoEntry.repo_path
    $repoInstructionSections = @()

    $repoAgentsPath = Join-Path $repoPath 'AGENTS.md'
    if (Test-Path $repoAgentsPath) {
        $repoInstructionSections += [ordered]@{
            name = "Repo AGENTS.md ($repoAgentsPath)"
            content = [System.IO.File]::ReadAllText($repoAgentsPath)
        }
    }

    $repoInstructionsDir = Join-Path $repoPath '.github/instructions'
    if (Test-Path $repoInstructionsDir) {
        $repoInstructionFiles = Get-ChildItem -LiteralPath $repoInstructionsDir -File -Filter '*.instructions.md' -ErrorAction SilentlyContinue | Sort-Object Name
        foreach ($repoInstructionFile in $repoInstructionFiles) {
            $repoInstructionSections += [ordered]@{
                name = "Repo instruction file ($($repoInstructionFile.Name))"
                content = [System.IO.File]::ReadAllText($repoInstructionFile.FullName)
            }
        }
    }

    $repoInstructionSummaryPath = Join-Path $instructionsRoot "$workspaceName.$repoId.instructions.md"
    New-GeneratedInstructionSummaryFile `
        -OutputPath $repoInstructionSummaryPath `
        -ApplyTo "workspaces/$workspaceName/repos/$repoId/**" `
        -Title "Repo instructions for $workspaceName/$repoId" `
        -Sections $repoInstructionSections
}

$statusTable = $repoStates | ForEach-Object {
    [pscustomobject]@{
        Repo = $_.repo_id
        Present = $_.present
        Ready = $_.readiness.state
        Recommended = $_.readiness.recommended_next_step
        Branch = $_.git.branch
    }
}

Write-Host "Workspace '$workspaceName' is active."
$statusTable | Format-Table -AutoSize
Write-Host "Generated workspace file: $workspaceFile"

if ($crgResults.Count -gt 0) {
    Write-Host ""
    Write-Host "Code-review-graph build (--skip-flows):"
    $crgResults | Format-Table -AutoSize
    Write-Host "Incremental updates fire automatically via the Copilot CLI subagentStop / sessionEnd hooks (helix/.github/hooks/scripts/crg-sweep.js)."
    Write-Host "Run '/build-graph' (or 'python -m code_review_graph update --repo <path>') to populate flows before review phases."
}

if (-not $SkipGraphBuild -and $crgMode -ne 'mcp') {
    Write-Host ""
    Write-Host "CRG mode is '$crgMode'. To enable graph-based retrieval, run: ./helix/scripts/set-context-provider.ps1 -Mode mcp -Bootstrap"
}
